baseURL = "https://elleryq.github.io/code-experiments/"
languageCode = "zh-tw"
title = "Code experiments"
theme = "ananke"
DefaultContentLanguage = "zh"
enableRobotsTXT = true

[params]
  twitter = "https://twitter.com/elleryq"
